SRE-2510: add license as expected by OpenSSF Scorecard
daos-stack/isa-l_crypto pull request #11
Opened 2024-09-30 07:14 UTC by grom72

Inherit BSD-2-Clause-Patent License
from the main - daos-stack/daos project.

2024-10-03 15:55 UTC, janekmi approved these changes

2024-10-04 08:06 UTC, janekmi requested changes

2024-10-04 08:06 UTC, janekmi commented on Makefile
> +# Copyright (c) 2019-2024 Intel Corporation
```suggestion
# Copyright (c) 2019-2024 Intel Corporation

```

2024-10-04 10:48 UTC, janekmi approved these changes

2024-10-04 11:01 UTC, osalyk approved these changes

2024-10-07 17:59 UTC, brianjmurrell requested changes
This failed to build.  You probably need to update the `packaging/` subdir from https://github.com/daos-stack/packaging/ by [cloning and] checking out `master` from that somewhere and then in the directory for this PR run `$path/to/packaging/master/install`.

2024-10-08 13:12 UTC, brianjmurrell requested changes
The CentOS 7 build seems to be failing still.  But the good news is that we can simply just stop building this on CentOS 7.

2024-10-08 13:29 UTC, grom72 commented
> The CentOS 7 build seems to be failing still. But the good news is that we can simply just stop building this on CentOS 7.

Done

2024-10-14 17:25 UTC, grom72 commented
Hi @daos-stack/release-engineering,
all tests passed. 
PR is ready for landing.

2024-10-15 12:12 UTC, merged